[project]
name = "qcodes_qick"
version = "0.0.0"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["qcodes_qick"]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "N", "B", "FA", "TCH"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"example_scripts/*" = ["F401", "F403", "F405"]
